email = "dinnerout.operation@gmail.com"
github = "veryfaraway"
#facebook = "yourfacebookusername"
#gitlab = "yourgitlabusername"
#linkedin = "yourlinkedinusername"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
